version: "3.7"

services:

  api:
    container_name: account
    build: ./account
    image: account:latest
    command: gunicorn -b :8080 main.wsgi
    expose:
      - "8080"
    networks:
      - backend

  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - backend
      - default

networks:
  backend: