version: "3.7"

services:

  db:
    image: postgres
    networks:
      - postgres

  api:
    container_name: account
    build: ./account
    image: account:latest
    command: sh -c "python3 manage.py migrate &&
                    gunicorn -b :8080 main.wsgi"
    expose:
      - "8080"
    networks:
      - backend
      - postgres
    depends_on:
      - db

  rebalance:
    container_name: rebalance
    image: account:latest
    command: sh -c "while true;
                    do python3 manage.py rebalance;
                    sleep 2; done"
    networks:
      - postgres
    depends_on:
      - db
      - api

  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - backend
      - default

networks:
  backend:
  postgres: