# Generated by Django 3.0.1 on 2019-12-26 08:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=500)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hold', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
