# Generated by Django 3.0.1 on 2019-12-26 09:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hold', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
